### PR TITLE
Unfold editor of new selection

### LINKED ISSUE #24: Goto folded row -> does not unfold
Given a simple JSON (or any other foldable code block):
image

When I fold it and then go to a line in between the folded code block:
image

Then I expect the code block to unfold and jump to the entered line.
Instead it remains folded.
image

Works at least in Sublime Text 3.

Atom: 1.0.10
OS: Win 8.1 64Bit

How to fix:
adding the following lines after https://github.com/atom/go-to-line/blob/master/lib/go-to-line-view.coffee#L68 unfolds the row
```js
if (editor.isFoldedAtBufferRow(position)) {
  editor.unfoldBufferRow(position)
}
```

### PR DESCRIPTION
**Pull request by joseramonc**
fix #24

### CODE REVIEW

**Comment by rossant** [comment]
Is there a plan to merge this?

**Comment by 50Wliu** [comment]
Sorry for the delay.  @joseramonc can you please add a test for this?

**Comment by 50Wliu** [comment]
In addition, this does not work when there are multiple folds as `editor.unfoldCurrentRow()` only unfolds by one level.

**Comment by kuychaco** [comment]
Thanks for the contribution @joseramonc :). I tweaked it to support the case of nested folds and included a test (https://github.com/atom/go-to-line/commit/b4be3c72db7436a3bc790bff2957bdc7c914f86c)

**Pull request merged**
