### PR TITLE
Auto navigation

### PR DESCRIPTION
**Pull request by nettofarah**
I took a stab at implementing auto-navigation.
https://github.com/atom/go-to-line/issues/26

### CODE REVIEW

**Comment by nettofarah** [comment]
auto-navigation

**Comment by nettofarah** [comment]
This should look even better after: https://github.com/atom/go-to-line/pull/31

**Comment by nettofarah** [comment]
hey @50Wliu.
Is there anything else I need to do to get this merged?

**Comment by nettofarah** [comment]
friendly reminder about this PR

**Comment by 50Wliu** [comment]
We have a large backlog of PRs, so reviewing takes some time to get to.

**Comment by humancopy** [comment]
Why is this or #36 not getting merged? This is so needed! 😄

**Comment by nettofarah** [comment]
I kind of gave up on merging anything to these packages already.
I made a series of PRs to a few of these packages but they never even got reviewed.

**Comment by ungb** [comment]
@nettofarah I was able to test your changes and everything looks good.  I went ahead and attempted to rebase master and make the changes in JS but didn't have access to push to this branch.  

I went then ahead to create PR https://github.com/atom/go-to-line/pull/53 that has basically the same changes you have here but in the JS files.


Really appreciate your work on this and really sorry it took so long to get some 👀  on this.  

Once you approve the other pr, I will merge it in.

**Comment by nettofarah** [comment]
Thanks, @ungb.
I would love to understand what's the prioritization process for atom packages and atom core.
I have made a series of PRs that never even got looked at.

I love atom and would love to help make it better, but I have to say that the dev experience has been pretty poor and that got me super demotivated.

Thanks for checking this out though :)

**Comment by 50Wliu** [comment]
> I would love to understand what's the prioritization process for atom packages and atom core.

We recently (as in, a few months ago) made some organizational changes so that we can more efficiently review PRs as they're opened instead of putting them on an ever-growing backlog and never getting to them.  So hopefully if you ever decide to contribute again you should see much faster turnaround times than before.  I can't discuss the exact process but essentially we put PRs onto a list that then gets periodically revisited and prioritized as necessary.

**Comment by nettofarah** [comment]
Great! Thanks, @50Wliu

**Comment by ungb** [comment]
Thanks for this PR @nettofarah! Really sorry about your experience.  As @50Wliu said,  we've made some process changes and will continue to find ways to be able to get faster turnaround on issues and PRs that are coming in. 

 
I merged https://github.com/atom/go-to-line/pull/53 and these changes will go out when 1.25.0 hits stable.

**Pull request closed without merging**
